spring:
  application:
    name: service

  datasource:
    url: jdbc:h2:file:./target/h2_database;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;
    username: h2_user
    password: h2_pass
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  batch:
    jdbc:
      initialize-schema: never

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          job-store:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
          data-source:
            myDS.driver: org.h2.Driver
            myDS.URL: jdbc:h2:file:./target/h2_database;
            myDS.user: h2_user
            myDS.password: = h2_pass
          scheduler:
            instanceName: demo-scheduler
            instanceId: AUTO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
    jmx:
      exposure:
        include: health, info
