server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
    jmx:
      exposure:
        include: health, info
